title: heathfarrow.dev
email: heath.farrow@gmail.com
name: "Heath Farrow"
# subtitle: "Software Developer"
description: >-
  The dev blog of video game developer Heath Farrow.
baseurl: ""
url: "https://heathfarrow.dev"
repository: hfarrow/hfarrow.github.io
twitter_username:
github_username:  hfarrow

author:
  name     : "Heath Farrow"
  avatar   :
  bio      : "A dedicated programmer in the video game industry since 2008. The opinions shared here do not represent those of his current or past employers."
  location : "Irvine, CA, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/heathfarrow"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hfarrow"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Additional Minimal Mistakes Settings
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
include: ["_pages"]

# TODO requires plugin
# paginate: 5
# paginate_path: /page:num/

search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
